<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Failed suite [Failed suite [Suite]]" duration-ms="85905" started-at="2020-09-23T06:13:06Z" finished-at="2020-09-23T06:14:32Z">
    <groups>
    </groups>
    <test name="Test(failed)(failed)" duration-ms="85905" started-at="2020-09-23T06:13:06Z" finished-at="2020-09-23T06:14:32Z">
      <class name="retry_FinalTests.TestNGExampleTests">
        <test-method status="PASS" signature="setup()[pri:0, instance:retry_FinalTests.TestNGExampleTests@5649fd9b]" name="setup" is-config="true" duration-ms="30218" started-at="2020-09-23T06:13:06Z" finished-at="2020-09-23T06:13:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="SKIP" signature="verifyLoginPageText()[pri:1, instance:retry_FinalTests.TestNGExampleTests@5649fd9b]" name="verifyLoginPageText" duration-ms="1781" started-at="2020-09-23T06:13:37Z" finished-at="2020-09-23T06:13:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Forced to fail]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Forced to fail
at org.testng.Assert.fail(Assert.java:96)
at retry_FinalTests.TestNGExampleTests.verifyLoginPageText(TestNGExampleTests.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginPageText -->
        <test-method status="PASS" signature="quitt()[pri:0, instance:retry_FinalTests.TestNGExampleTests@5649fd9b]" name="quitt" is-config="true" duration-ms="5611" started-at="2020-09-23T06:13:38Z" finished-at="2020-09-23T06:13:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitt -->
        <test-method status="PASS" signature="setup()[pri:0, instance:retry_FinalTests.TestNGExampleTests@5649fd9b]" name="setup" is-config="true" duration-ms="5124" started-at="2020-09-23T06:13:44Z" finished-at="2020-09-23T06:13:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="verifyLoginPageText()[pri:1, instance:retry_FinalTests.TestNGExampleTests@5649fd9b]" name="verifyLoginPageText" duration-ms="5127" started-at="2020-09-23T06:13:49Z" finished-at="2020-09-23T06:13:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Forced to fail]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Forced to fail
at org.testng.Assert.fail(Assert.java:96)
at retry_FinalTests.TestNGExampleTests.verifyLoginPageText(TestNGExampleTests.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginPageText -->
        <test-method status="PASS" signature="quitt()[pri:0, instance:retry_FinalTests.TestNGExampleTests@5649fd9b]" name="quitt" is-config="true" duration-ms="6015" started-at="2020-09-23T06:13:54Z" finished-at="2020-09-23T06:14:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitt -->
        <test-method status="PASS" signature="setup()[pri:0, instance:retry_FinalTests.TestNGExampleTests@5649fd9b]" name="setup" is-config="true" duration-ms="5863" started-at="2020-09-23T06:14:00Z" finished-at="2020-09-23T06:14:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="verifyForgotPasswordPage()[pri:2, instance:retry_FinalTests.TestNGExampleTests@5649fd9b]" name="verifyForgotPasswordPage" duration-ms="11195" started-at="2020-09-23T06:14:06Z" finished-at="2020-09-23T06:14:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyForgotPasswordPage -->
        <test-method status="PASS" signature="quitt()[pri:0, instance:retry_FinalTests.TestNGExampleTests@5649fd9b]" name="quitt" is-config="true" duration-ms="14890" started-at="2020-09-23T06:14:17Z" finished-at="2020-09-23T06:14:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitt -->
      </class> <!-- retry_FinalTests.TestNGExampleTests -->
    </test> <!-- Test(failed)(failed) -->
  </suite> <!-- Failed suite [Failed suite [Suite]] -->
</testng-results>
