<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" ignored="0" total="6" passed="2">
  <reporter-output>
    <line>
      <![CDATA[Strating Test]]>
    </line>
    <line>
      <![CDATA[Starting test:->method1]]>
    </line>
    <line>
      <![CDATA[Strating Test]]>
    </line>
    <line>
      <![CDATA[Starting test:->method1]]>
    </line>
    <line>
      <![CDATA[Strating Test]]>
    </line>
    <line>
      <![CDATA[Starting test:->method1]]>
    </line>
    <line>
      <![CDATA[Strating Test]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="150" started-at="2020-09-20T15:27:29Z" finished-at="2020-09-20T15:27:29Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="150" started-at="2020-09-20T15:27:29Z" finished-at="2020-09-20T15:27:29Z">
      <class name="retry.RetryFailed">
        <test-method status="SKIP" signature="method1()[pri:0, instance:retry.RetryFailed@5cb9f472]" name="method1" duration-ms="21" started-at="2020-09-20T15:27:29Z" finished-at="2020-09-20T15:27:29Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed
at org.testng.Assert.fail(Assert.java:96)
at retry.RetryFailed.method1(RetryFailed.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Strating Test]]>
            </line>
            <line>
              <![CDATA[Starting test:->method1]]>
            </line>
          </reporter-output>
        </test-method> <!-- method1 -->
        <test-method status="SKIP" signature="method1()[pri:0, instance:retry.RetryFailed@5cb9f472]" name="method1" duration-ms="4" started-at="2020-09-20T15:27:29Z" finished-at="2020-09-20T15:27:29Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed
at org.testng.Assert.fail(Assert.java:96)
at retry.RetryFailed.method1(RetryFailed.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Strating Test]]>
            </line>
            <line>
              <![CDATA[Starting test:->method1]]>
            </line>
          </reporter-output>
        </test-method> <!-- method1 -->
        <test-method status="SKIP" signature="method1()[pri:0, instance:retry.RetryFailed@5cb9f472]" name="method1" duration-ms="4" started-at="2020-09-20T15:27:29Z" finished-at="2020-09-20T15:27:29Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed
at org.testng.Assert.fail(Assert.java:96)
at retry.RetryFailed.method1(RetryFailed.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Strating Test]]>
            </line>
            <line>
              <![CDATA[Starting test:->method1]]>
            </line>
          </reporter-output>
        </test-method> <!-- method1 -->
        <test-method status="FAIL" signature="method1()[pri:0, instance:retry.RetryFailed@5cb9f472]" name="method1" duration-ms="2" started-at="2020-09-20T15:27:29Z" finished-at="2020-09-20T15:27:29Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed
at org.testng.Assert.fail(Assert.java:96)
at retry.RetryFailed.method1(RetryFailed.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Strating Test]]>
            </line>
          </reporter-output>
        </test-method> <!-- method1 -->
        <test-method status="PASS" signature="method2()[pri:0, instance:retry.RetryFailed@5cb9f472]" name="method2" duration-ms="2" started-at="2020-09-20T15:27:29Z" finished-at="2020-09-20T15:27:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method2 -->
        <test-method status="PASS" signature="method3()[pri:0, instance:retry.RetryFailed@5cb9f472]" name="method3" duration-ms="3" started-at="2020-09-20T15:27:29Z" finished-at="2020-09-20T15:27:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method3 -->
      </class> <!-- retry.RetryFailed -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
